export type Color = 'Black' | 'Blue' | 'Yellow' | 'Green' | 'White'

export type StaticValues = {
  id: number,
  color: Color,
  angle:  number,
  distance: number,
  distanceInDegree: number,
  bottle: boolean

}

const angleOffSet = 2;
const distanceOffSet = -90;

export const staticA: StaticValues[] = [
	{
		id: 0,
		color: 'Black',
		angle: angleOffSet + 26.6,
		distance: distanceOffSet + 720 + 110,
		distanceInDegree: ((730.6 + 20) / 57) * 360,
		bottle: false,
	},
	{
		id: 1,
		color: 'Black',
		angle: angleOffSet + 19.4 - 0.5,
		distance: distanceOffSet + 682.8 + 100 ,
		distanceInDegree: (730.6 / 50.265) * 360,
		bottle: false,
	},
	{
		id: 2,
		color: 'Black',
		angle: angleOffSet + 11.6 - 2,
		distance: distanceOffSet + 657.4 + 50,
		distanceInDegree: (730.6 / 50.265) * 360,
		bottle: false,
	},
	{
		id: 3,
		color: 'Black',
		angle: angleOffSet + 30.4 + 1,
		distance: distanceOffSet + 635.6 + 90,
		distanceInDegree: 0,
		bottle: false,
	},
	{
		id: 4,
		color: 'Black',
		angle: angleOffSet + 22.5 ,
		distance: distanceOffSet + 593.2 + 60,
		distanceInDegree: 0,
		bottle: false,
	},
	{
		id: 5,
		color: 'Black',
		angle: angleOffSet + 13.5 ,
		distance: distanceOffSet + 563.7 + 50,
		distanceInDegree: 0,
		bottle: false,
	},
	{
		id: 6,
		color: 'Black',
		angle: angleOffSet + 35.5 + 1 ,
		distance: distanceOffSet + 555 + 80,
		distanceInDegree: 0,
		bottle: false,
	},
	{
		id: 7,
		color: 'Black',
		angle: angleOffSet + 26.7,
		distance: distanceOffSet + 505.8 + 50,
		distanceInDegree: 0,
		bottle: false,
	},
	{
		id: 8,
		color: 'Black',
		angle: angleOffSet + 16.3,
		distance: distanceOffSet + 470.9 + 20,
		distanceInDegree: 0,
		bottle: false,
	},
	{
		id: 9,
		color: 'Black',
		angle: angleOffSet + 42.1 + 2,
		distance: distanceOffSet + 480 + 60,
		distanceInDegree: 0,
		bottle: false,
	},
	{
		id: 10,
		color: 'Black',
		angle: angleOffSet + 32.5 + 2,
		distance: distanceOffSet + 422.2 + 30,
		distanceInDegree: ((338.3 + 20) / 57) * 360,
		bottle: false,
	},
	{
		id: 11,
		color: 'Black',
		angle: angleOffSet + 20.3 + 1,
		distance: distanceOffSet + 379.7,
		distanceInDegree: ((338.3 + 20) / 57) * 360,
		bottle: false,
	},
];

export const staticB: StaticValues[] = [
	{
		id: 0,
		color: 'Black',
		angle: -angleOffSet - 15.5 - 4,
		distance: distanceOffSet + 686.1 + 60,
		distanceInDegree: ((730.6 + 20) / 57) * 360,
		bottle: false,
	},
	{
		id: 1,
		color: 'Black',
		angle: -angleOffSet - 23 - 5,
		distance: distanceOffSet + 699.5 + 90,
		distanceInDegree: (730.6 / 50.265) * 360,
		bottle: false,
	},
	{
		id: 2,
		color: 'Black',
		angle: -angleOffSet - 29.7 - 4,
		distance: distanceOffSet + 741.7 + 110,
		distanceInDegree: (730.6 / 50.265) * 360,
		bottle: false,
	},
	{
		id: 3,
		color: 'Black',
		angle: -angleOffSet - 18 - 4,
		distance: distanceOffSet + 576.2 + 40,
		distanceInDegree: 0,
		bottle: false,
	},
	{
		id: 4,
		color: 'Black',
		angle: -angleOffSet - 26.5 - 5,
		distance: distanceOffSet + 612.2 + 60,
		distanceInDegree: 0,
		bottle: false,
	},
	{
		id: 5,
		color: 'Black',
		angle: -angleOffSet - 33.9 - 5,
		distance: distanceOffSet + 660.1 + 80,
		distanceInDegree: 0,
		bottle: false,
	},
	{
		id: 6,
		color: 'Black',
		angle: -angleOffSet - 21.5 - 5,
		distance: distanceOffSet + 485.8 + 10,
		distanceInDegree: 0,
		bottle: false,
	},
	{
		id: 7,
		color: 'Black',
		angle: -angleOffSet - 31.1 - 6,
		distance: distanceOffSet + 528 + 40,
		distanceInDegree: 0,
		bottle: false,
	},
	{
		id: 8,
		color: 'Black',
		angle: -angleOffSet - 39.2 - 6,
		distance: distanceOffSet + 582.9 + 50,
		distanceInDegree: 0,
		bottle: false,
	},
	{
		id: 9,
		color: 'Black',
		angle: -angleOffSet - 26.6 - 5,
		distance: distanceOffSet + 398 - 30,
		distanceInDegree: 0,
		bottle: false,
	},
	{
		id: 10,
		color: 'Black',
		angle: -angleOffSet - 37.5 - 8,
		distance: distanceOffSet + 448.6 + 10,
		distanceInDegree: ((338.3 + 20) / 57) * 360,
		bottle: false,
	},
	{
		id: 11,
		color: 'Black',
		angle: -angleOffSet - 46 - 7,
		distance: distanceOffSet + 512 + 40,
		distanceInDegree: ((338.3 + 20) / 57) * 360,
		bottle: false,
	},
];